[project]
name = "epub"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "lxml>=6.0.1",
]

[project.scripts]
epub-to-zip = "epub_2_zip:main"
format-xhtml = "format_xhtml:main"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages]
find = { where = ["src"] }
